[package]
name = "tust"
version = "0.1.0-dev3"
edition = "2024"

[dependencies]
tokio = { version = "1.38", features = ["full"] }
tempfile = "3.10"
diff = "0.1.13"
clap = { version = "4.5", features = ["derive"] }
colored = "2.1"
log = "0.4"
env_logger = "0.11"

[profile.release]
lto = true